# Target specific macros
TARGET = Speaker

TARGET_CPP_SOURCES = sample.cpp
	
TOPPERS_OSEK_OIL_SOURCE = sample.oil

# define the following macros to test the Speaker.playWav API
#WAV_SOURCES = lego_mindstorms_nxt.wav
#USER_DEF += PLAY_WAV
#BUILD_MODE = ROM_ONLY

# Don't modify below part
O_PATH ?= build

# makefile for C++(.cpp) build
include ../../../ecrobot/ecrobot++.mak
