# Target specific macros
TARGET = nxt_remocon
TARGET_SOURCES := \
	ecrobot_main.c \
	Joystick_app.c \
	Joystick_app_data.c \
	rt_matmultrr_sgl.c
TOPPERS_OSEK_OIL_SOURCE := ./ecrobot.oil

O_PATH ?= build

include ../../ecrobot/ecrobot.mak
