# Target specific macros
TARGET = sprite_text
	
TARGET_CC_SOURCES = \
	App.cc	\
	main.cc
	
TOPPERS_OSEK_OIL_SOURCE = ./main.oil
SPR_SOURCES = \
	./sprites/nxtOSEK.spr	\
	./sprites/rocks.spr	\

O_PATH ?= build
include ../../../ecrobot/ecrobot.mak
