# Target specific macros
TARGET = bmpfiledraw

TARGET_CPP_SOURCES = \
	BmpFileDraw.cpp \
	sample.cpp

BMP_SOURCES = \
	./RCXintro_1.bmp \
	./RCXintro_2.bmp \
	./RCXintro_3.bmp \
	./RCXintro_4.bmp \
	./RCXintro_5.bmp \
	./RCXintro_6.bmp \
	./RCXintro_7.bmp \
	./RCXintro_8.bmp \
	./RCXintro_9.bmp \
	./RCXintro_10.bmp \
	./RCXintro_11.bmp \
	./RCXintro_12.bmp \
	./RCXintro_13.bmp \
	./RCXintro_14.bmp \
	./RCXintro_15.bmp \
	./RCXintro_16.bmp
	
TOPPERS_OSEK_OIL_SOURCE = ./sample.oil

# Don't modify below part
O_PATH ?= build

# makefile for C++(.cpp) build
include ../../../ecrobot/ecrobot++.mak
