# Target specific macros
#

#
# This should be set to the basename of the executable
#

TARGET = SmartPointerTest

#
# List all .cc source files here
#
# Sections also available for .c sources
#

TARGET_CC_SOURCES := \
	SmartPtrTest.cc	\

#TARGET_SOURCES := \

#
# Set this to the name of your .oil source file
#

TOPPERS_OSEK_OIL_SOURCE := ./SmartPointerTest.oil

#
# This sample could be stored in only ROM
BUILD_MODE = ROM_ONLY

#
# These should be left alone normally
#

O_PATH ?= build

include ../../../ecrobot/ecrobot.mak
