# Target specific macros
TARGET = BTConnection

USER_DEF = MASTER_DEVICE
#USER_DEF = SLAVE_DEVICE

TARGET_CPP_SOURCES = sample.cpp
	
TOPPERS_OSEK_OIL_SOURCE = ./sample.oil

# Don't modify below part
O_PATH ?= build

# makefile for C++(.cpp) build
include ../../../ecrobot/ecrobot++.mak
