TARGET = SmartPointer

#
# user include path
#
USER_INC_PATH = ./boost

#
# List all .cpp source files here
#
# Sections also available for .c sources
#
TARGET_CPP_SOURCES = \
	./sample.cpp

TARGET_SOURCES = \
	./nxtAssert.c

#
# Set this to the name of your .oil source file
#

TOPPERS_OSEK_OIL_SOURCE = ./sample.oil

#
# These should be left alone normally
#

O_PATH ?= build

include ../../../ecrobot/ecrobot++.mak
