# It needs to define this macro to use TOPPERS/JSP
TOPPERS_KERNEL = NXT_JSP

# Target specific macros
TARGET = helloworld_JSP
TARGET_SOURCES = \
	helloworld.c
TOPPERS_JSP_CFG_SOURCE = ./helloworld.cfg

# Don't modify below part
O_PATH ?= build
include ../../ecrobot/ecrobot.mak
