# Target specific macros
TARGET = sprite_anime
	
TARGET_CC_SOURCES = \
	App.cc	\
	main.cc	\
	
TOPPERS_OSEK_OIL_SOURCE = ./main.oil

SPR_SOURCES = \
	./sprites/shiki_intro.spr \
	./sprites/shiki_walkforward.spr	\
	./sprites/shiki_taunt.spr	\
	./sprites/shiki_breathe.spr

O_PATH ?= build
include ../../../ecrobot/ecrobot.mak
