# Target specific macros
#

#
# This should be set to the basename of the executable
#

TARGET = PSPNxTest

#
# List all .cc source files here
#
# Sections also available for .c sources
#

TARGET_CC_SOURCES := \
	PSPNxTest.cc

#
# Set this to the name of your .oil source file
#

TOPPERS_OSEK_OIL_SOURCE := ./PSPNxTest.oil

#
# These should be left alone normally
#

C_OPTIMISATION_FLAGS = -Os

O_PATH ?= build

include ../../../ecrobot/ecrobot.mak
