# Target specific macros
#

#
# This should be set to the basename of the executable
#

TARGET = cpptest1

#
# List all .cc source files here
#
# Sections also available for .c sources
#

TARGET_CC_SOURCES := cpptest1.cc

#
# Set this to the name of your .oil source file
#

TOPPERS_OSEK_OIL_SOURCE := ./cpptest1.oil

#
# These should be left alone normally
#

O_PATH ?= build

include ../../../ecrobot/ecrobot.mak
