#HITECHNIC = IR_SEEKER
HITECHNIC = COLOR
#HITECHNIC = COMPASS

USER_DEF = $(HITECHNIC)

# Target specific macros
TARGET = $(HITECHNIC)
TARGET_SOURCES = ./hitechtest.c
TOPPERS_OSEK_OIL_SOURCE = ./hitechtest.oil

O_PATH ?= build
include ../../ecrobot/ecrobot.mak
