# Target specific macros
TARGET = daq

TARGET_CPP_SOURCES = sample.cpp
	
TOPPERS_OSEK_OIL_SOURCE = ./sample.oil

# Don't modify below part
O_PATH ?= build

# makefile for C++(.cpp) build
include ../../../ecrobot/ecrobot++.mak
