# Target specific macros
TARGET = main
	
TARGET_CC_SOURCES = \
	App.cc	\
	main.cc	\

#	Sprite.cc \
#	Screen.cc
	
TOPPERS_OSEK_OIL_SOURCE = ./main.oil
SPR_SOURCES = \
	shiki_intro.spr \
	shiki_walkforward.spr	\
	shiki_taunt.spr	\
	shiki_breathe.spr	\
	nxtOSEK.spr	\
	rocks.spr	\
	backdrop.spr

C_OPTIMISATION_FLAGS = -Os

O_PATH ?= build
include ../../../ecrobot/ecrobot.mak
