var files =
[
    [ "device/AccelSensor.h", null, null ],
    [ "device/Bluetooth.h", null, null ],
    [ "device/Camera.h", null, null ],
    [ "device/Clock.h", null, null ],
    [ "device/ColorSensor.h", null, null ],
    [ "device/CompassSensor.h", null, null ],
    [ "device/GyroSensor.h", null, null ],
    [ "device/I2c.h", null, null ],
    [ "device/IrSeeker.h", null, null ],
    [ "device/Lcd.h", null, null ],
    [ "device/LegoLight.h", null, null ],
    [ "device/LightSensor.h", null, null ],
    [ "device/Motor.h", null, null ],
    [ "device/Nxt.h", null, null ],
    [ "device/NxtColorSensor.h", null, null ],
    [ "device/Port.h", "_port_8h.html", "_port_8h" ],
    [ "device/PSPNx.h", null, null ],
    [ "device/RcxLightSensor.h", null, null ],
    [ "device/Rs485.h", null, null ],
    [ "device/Sensor.h", null, null ],
    [ "device/SonarSensor.h", null, null ],
    [ "device/SoundSensor.h", null, null ],
    [ "device/Speaker.h", null, null ],
    [ "device/TouchSensor.h", null, null ],
    [ "device/Usb.h", null, null ],
    [ "util/BTConnection.h", null, null ],
    [ "util/Daq.h", null, null ],
    [ "util/GamePad.h", null, null ],
    [ "util/Vector.h", null, null ]
];