# Target specific macros
TARGET = bmptest
TARGET_SOURCES := \
	bmptest.c
TOPPERS_OSEK_OIL_SOURCE := ./bmptest.oil
BMP_SOURCES := \
	RCXintro_1.bmp \
	RCXintro_2.bmp \
	RCXintro_3.bmp \
	RCXintro_4.bmp \
	RCXintro_5.bmp \
	RCXintro_6.bmp \
	RCXintro_7.bmp \
	RCXintro_8.bmp \
	RCXintro_9.bmp \
	RCXintro_10.bmp \
	RCXintro_11.bmp \
	RCXintro_12.bmp \
	RCXintro_13.bmp \
	RCXintro_14.bmp \
	RCXintro_15.bmp \
	RCXintro_16.bmp

O_PATH ?= build

include ../../ecrobot/ecrobot.mak
