# Target specific macros
TARGET = constdevice

TARGET_CPP_SOURCES = \
	ConstDevice.cpp \
	sample.cpp
	
TOPPERS_OSEK_OIL_SOURCE = ./sample.oil

# Don't modify below part
O_PATH ?= build

# makefile for C++(.cpp) build
include ../../../ecrobot/ecrobot++.mak
